name: PDU Server
slug: pdu-server
description: 'MQTT控制的PDU服务器，用于远程电源管理'
url: https://github.com/jeesa/addons/pdu-server
version: v1.0.2
image: jeesa/pdu-server
arch:
  - aarch64
  - amd64
apparmor: true

# 把端口从固定改成可配置项
ports:
  "{pdu_port}/tcp": pdu_port
ports_description:
  "{pdu_port}": PDU control port

privileged:
  - SYS_ADMIN
init: false
startup: application
boot: manual

options:
  pdu_port: 4600
  mqtt_host: "192.168.2.4"
  mqtt_port: 1883
  mqtt_user: "iot"
  mqtt_password: "password123"
  mqtt_base_topic: "icpdu/switch"

schema:
  pdu_port: int
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_base_topic: str
