name: "PDU Server"
version: "v1.0.2"
slug: "pdu_server"
codenotary: jeesa@example.com   # 可替换为你的邮箱
description: "MQTT控制的PDU服务器，用于远程电源管理。"
image: jeesa/pdu-server
url: https://github.com/jeesa/addons/pdu-server
init: false
arch:
  - aarch64
  - amd64
apparmor: true
privileged:
  - SYS_ADMIN
startup: application
boot: manual

# 端口从固定改为可配置项（绑定到选项中的 pdu_port）
ports:
  "{pdu_port}/tcp": pdu_port
ports_description:
  "{pdu_port}": "PDU control port"
ports_description:
  4600/tcp: 'socket server port'
ports:
  4600/tcp: 4600
options:
  mqtt_host: "192.168.2.4"
  mqtt_port: 1883
  mqtt_user: "iot"
  mqtt_password: "password123"
  mqtt_base_topic: "icpdu/switch"

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_base_topic: str
