name: "PDU Server"
version: "1.0.2"
slug: "pdu_server"
codenotary: zhz@honry.net
description: "MQTT控制的PDU服务器，用于远程电源管理。"
image: jeesa/pdu-server
url: https://github.com/jeesa/addons/pdu-server
init: false
boot: manual
arch:
  - aarch64
  - amd64
apparmor: true
privileged:
  - SYS_ADMIN
startup: application

ports:
  "4600/tcp": 4600   # 默认对外暴露端口，如果用户想改只能改这里
ports_description:
  "4600/tcp": "PDU control port"

options:
  mqtt_host: "192.168.2.4"
  mqtt_port: 1883
  mqtt_user: "iot"
  mqtt_password: "password123"
  mqtt_base_topic: "icpdu/switch"

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_base_topic: str
